language: python
python:
  - "3.6"
  - "3.7"

script:
  - pip install -U .

before_deploy:
  - echo "$TRAVIS_TAG" > VERSION

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
